---
# Paths
Db: /var/lib/kurrent
Index: /var/lib/kurrent/index
Log: /var/log/kurrent

# Certificates configuration
CertificateFile: /etc/kurrentdb/certs/node.crt
CertificatePrivateKeyFile: /etc/kurrentdb/certs/node.key
TrustedRootCertificatesPath: /etc/kurrentdb/certs/ca

# Network configuration
NodeIp: 0.0.0.0
NodePort: 2113
EnableAtomPubOverHTTP: true

# Projections configuration
RunProjections: All

# Limit max append size to 1MB for tests (matches pre-v26 default)
MaxAppendSize: 1048576
MaxAppendEventSize: 1048576
